
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/**
 * CUP generated interface containing symbol constants.
 */
public interface JSymbol {
    /* terminals */
    public static final int DIVEQ = 31;
    public static final int STR = 37;
    public static final int MODEQ = 32;
    public static final int GREATER = 17;
    public static final int LESS = 16;
    public static final int MINUS = 19;
    public static final int GREQ = 24;
    public static final int AND = 26;
    public static final int NUMTYPE = 40;
    public static final int OR = 27;
    public static final int BOOL = 41;
    public static final int COMMA = 13;
    public static final int INC = 35;
    public static final int DIV = 21;
    public static final int PLUSEQ = 28;
    public static final int NUM = 39;
    public static final int PLUS = 18;
    public static final int IF = 3;
    public static final int STRTYPE = 38;
    public static final int EXCL = 34;
    public static final int EOF = 0;
    public static final int MINEQ = 29;
    public static final int RETURN = 8;
    public static final int EQUAL = 15;
    public static final int error = 1;
    public static final int MUL = 20;
    public static final int MOD = 33;
    public static final int NEQ = 23;
    public static final int BR = 10;
    public static final int BREAK = 7;
    public static final int EQ = 22;
    public static final int MULEQ = 30;
    public static final int BL = 9;
    public static final int BOOLTYPE = 42;
    public static final int ELSE = 4;
    public static final int STOP = 14;
    public static final int WHILE = 2;
    public static final int LEQ = 25;
    public static final int CBR = 12;
    public static final int DEF = 5;
    public static final int DEC = 36;
    public static final int CBL = 11;
    public static final int VAR = 43;
    public static final int PRINT = 6;
    public static final String[] terminalNames = new String[]{
            "EOF",
            "error",
            "WHILE",
            "IF",
            "ELSE",
            "DEF",
            "PRINT",
            "BREAK",
            "RETURN",
            "BL",
            "BR",
            "CBL",
            "CBR",
            "COMMA",
            "STOP",
            "EQUAL",
            "LESS",
            "GREATER",
            "PLUS",
            "MINUS",
            "MUL",
            "DIV",
            "EQ",
            "NEQ",
            "GREQ",
            "LEQ",
            "AND",
            "OR",
            "PLUSEQ",
            "MINEQ",
            "MULEQ",
            "DIVEQ",
            "MODEQ",
            "MOD",
            "EXCL",
            "INC",
            "DEC",
            "STR",
            "STRTYPE",
            "NUM",
            "NUMTYPE",
            "BOOL",
            "BOOLTYPE",
            "VAR"
    };
}

