
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 30;
  public static final int STR = 36;
  public static final int GREATER = 16;
  public static final int LESS = 15;
  public static final int MINUS = 18;
  public static final int GREQ = 23;
  public static final int AND = 25;
  public static final int NUMTYPE = 35;
  public static final int OR = 26;
  public static final int BOOL = 32;
  public static final int COMMA = 12;
  public static final int DIV = 20;
  public static final int PLUSEQ = 27;
  public static final int NUM = 34;
  public static final int PLUS = 17;
  public static final int IF = 4;
  public static final int STRTYPE = 37;
  public static final int EOF = 0;
  public static final int MINEQ = 28;
  public static final int RETURN = 2;
  public static final int EQUAL = 14;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int NEQ = 22;
  public static final int BR = 9;
  public static final int EQ = 21;
  public static final int MULEQ = 29;
  public static final int BL = 8;
  public static final int BOOLTYPE = 33;
  public static final int ELSE = 5;
  public static final int STOP = 13;
  public static final int WHILE = 3;
  public static final int LEQ = 24;
  public static final int CBR = 11;
  public static final int DEF = 6;
  public static final int CBL = 10;
  public static final int VAR = 31;
  public static final int PRINT = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RETURN",
  "WHILE",
  "IF",
  "ELSE",
  "DEF",
  "PRINT",
  "BL",
  "BR",
  "CBL",
  "CBR",
  "COMMA",
  "STOP",
  "EQUAL",
  "LESS",
  "GREATER",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "EQ",
  "NEQ",
  "GREQ",
  "LEQ",
  "AND",
  "OR",
  "PLUSEQ",
  "MINEQ",
  "MULEQ",
  "DIVEQ",
  "VAR",
  "BOOL",
  "BOOLTYPE",
  "NUM",
  "NUMTYPE",
  "STR",
  "STRTYPE"
  };
}

