package parser.parsetree;

/**
 * This is a wrapper class for binary conditional expressions.
 * Its instances will hold an assignment operator and two operands.
 */
public class BinaryCondition extends ConditionalExpression {

    private final BinOp op;
    private final Object operand1;
    private final Object operand2;

    /**
     * This constructor will instantiate a wrapper for a binary conditional expression.
     *
     * @param op    the operator.
     * @param o1    the first operand.
     * @param o2    the second operand.
     * @param left  the start index.
     * @param right the end index.
     */
    BinaryCondition(Object op, Object o1, Object o2, int left, int right) {
        super(left, right);
        this.operand1 = o1;
        this.operand2 = o2;
        this.op = BinOp.getByLiteral(op.toString());
    }

    /**
     * Returns the binary operator.
     *
     * @return the operator.
     */
    public BinOp getOperator() {
        return op;
    }

    /**
     * Returns the first operand.
     *
     * @return the first operand.
     */
    public Object getOperand1() {
        return operand1;
    }

    /**
     * Returns the second operand.
     *
     * @return the second operand.
     */
    public Object getOperand2() {
        return operand2;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     *
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        if (op != null) {
            return "(" + operand1.toString() + " " + op.getLiteral() + " " + operand2.toString() + ")";
        }
        return "(" + operand1.toString() + ")";
    }

    /**
     * This method returns the binary condition as representation of the parse tree.
     *
     * @return a snipped of the parse tree.
     */
    @Override
    public String getParseTree() {
        StringBuilder out = getStringBuilder(this);
        appendKeyword(out, Keyword.BL, 1);
        evaluateExpression(out, operand1, 1);
        appendLine(out, "ConditionalOperator", 1);
        appendBinOp(out, op, 2);
        evaluateExpression(out, operand2, 1);
        appendKeyword(out, Keyword.BR, 1);
        return out.toString();
    }

}
