package parser.parsetree;

import java.util.ArrayList;
import java.util.List;

/**
 * This is a wrapper class for binary conditional expressions.
 * Its instances will hold an assignment operator and two operands.
 */
public class BinaryCondition extends ConditionalExpression {

    private BinOp op;
    private Object operand1;
    private Object operand2;

    public BinaryCondition(Object o1) {
        this.operand1 = o1;
    }

    public BinaryCondition(Object op, Object o1, Object o2) {
        this(o1);
        this.operand2 = o2;
        this.op = BinOp.getName(op.toString());
    }

    public Object getOperand1() {
        return operand1;
    }

    public Object getOperand2() {
        return operand2;
    }

    public BinOp getOperator() {
        return op;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        if (op != null) {
            return "(" + operand1.toString() + " " + op.asString() + " " + operand2.toString() + ")";
        }
        return "(" + operand1.toString() + ")";
    }

}
