package parser.parsetree;

import parser.parsetree.interfaces.Visitor;

import java.util.ArrayList;
import java.util.List;

/**
 * This is a wrapper class for constants. A constant may be an expression or a value of any type.
 */
public class Constant extends Statement {

    private Object obj;

    public Constant(Object o) {
        this.obj = o;
    }

    public Object getValue() {
        return obj;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        return obj.toString();
    }

}
