package parser.parsetree;

import parser.parsetree.interfaces.Visitor;

import java.util.ArrayList;
import java.util.List;

/**
 * This is a wrapper class for function call statements.
 * It holds the identifier and a parameter list.
 */
public class FunctionCallStatement extends Statement {


    private String identifier;
    private List<Statement> parameterList = new ArrayList<>();

    public FunctionCallStatement(Object identifier) {
        this.identifier = identifier.toString();
    }

    public FunctionCallStatement(Object identifier, Object params) {
        this(identifier);
        if (params != null) {
            this.parameterList = ((Argument) params).getStatements();
        }
    }

    public String getIdentifier() {
        return identifier;
    }

    public int getParamCount() {
        return parameterList.size();
    }

    public List<Statement> getArgumentList() {
        return parameterList;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        String out = identifier + "(";
        for (int i = 0; i < parameterList.size(); i++) {
            out += parameterList.get(i);
            if (i != parameterList.size()-1) {
                out += ", ";
            }
        }
        out += ");\n";

        return out;
    }

    /**
     * This method accepts a visitor. The visitor will then have access to this instance
     * for code validation and execution.
     * @param visitor the visitor to accept.
     */
    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }
}
