package parser.parsetree;

import parser.parsetree.interfaces.Visitor;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * This is a wrapper class for if-then statements.
 * It holds one condition and the statement list, and may be used as component for an if-then-else statement.
 */
public class IfThenStatement extends Component {

    protected Object condition;
    protected List<Component> componentListIf = new ArrayList<>();

    /**
     * This constructor will wrap an if-then statement.
     * While the conditional statement is mandatory, nested statements are optional.
     *
     * @param condition      the conditional expression.
     * @param statementList1 the statement list for the if-then body.
     */
    public IfThenStatement(Object condition, Object statementList1, int left, int right) {
        super(left, right);
        this.condition = condition;
        if (statementList1 != null) {
            this.componentListIf.addAll(((Component) statementList1).getStatements());
        }
    }

    /**
     * Returns the conditional expression.
     *
     * @return the conditional expression.
     */
    public Object getCondition() {
        return condition;
    }

    /**
     * Returns the statement list of the if-else body.
     *
     * @return the statement list.
     */
    @Override
    public List<Component> getStatements() {
        List<Component> components = new ArrayList<>();
        if (!componentListIf.isEmpty()) {
            components.addAll(componentListIf);
        }
        return components;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     *
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        StringBuilder out = new StringBuilder("\nif ");
        boolean isCond = condition instanceof ConditionalExpression;
        if (!isCond) {
            out.append("(");
        }
        out.append(condition);
        if (!isCond) {
            out.append(")");
        }
        out.append(" {\n");
        if (!componentListIf.isEmpty()) {
            List<String> componentStrings = new ArrayList<>();
            for (Component st : componentListIf) {
                componentStrings.addAll(Arrays.asList(st.toString().split("\n")));
            }
            for (String str : componentStrings) {
                out.append("\t").append(str).append("\n");
            }
        }

        out.append("}\n\n");
        return out.toString();
    }

    /**
     * This method returns the if-then statement as representation of the parse tree.
     *
     * @return a snipped of the parse tree.
     */
    @Override
    public String getParseTree() {
        StringBuilder out = new StringBuilder(this.getClass().getName());
        out = new StringBuilder("+ " + out.substring(out.lastIndexOf(".") + 1) + "\n");
        out.append("\t+ " + "IF" + "\n");
        out.append("\t\t+ " + "CONDITION" + "\n");
        String[] conditionComponents = (((Component) condition)).getParseTree().split("\n");
        for (String str : conditionComponents) {
            out.append("\t\t\t ").append(str).append("\n");
        }
        if (!componentListIf.isEmpty()) {
            out.append("\t\t+ " + "BODY" + "\n");
            for (Component c : componentListIf) {
                String[] components = (c).getParseTree().split("\n");
                for (String str : components) {
                    out.append("\t\t\t ").append(str).append("\n");
                }
            }
        }
        return out.toString();
    }

    /**
     * This method accepts a visitor. The visitor will then have access to this instance
     * for code validation and execution.
     *
     * @param visitor the visitor to accept.
     */
    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }
}
