package parser.parsetree;

import parser.parsetree.interfaces.Declaration;
import parser.parsetree.interfaces.Visitor;

import java.util.ArrayList;
import java.util.List;

/**
 * This is a wrapper class for parameter declarations of a function body.
 * It is constructed like a linked list. The leftmost declaration points to its neighbor to the right, etc.
 */
public class ParamDeclaration extends Statement implements Declaration {

    private Type type;
    private String identifier;
    private Object value;
    private Object initValue;
    private ParamDeclaration next;

    ParamDeclaration(Object type, Object identifier) {
        this.type = Type.getByName(type);
        this.identifier = identifier.toString();
        if (this.type == Type.BOOLEAN) {
            value = false;
        } else if (this.type == Type.NUMERIC) {
            value = 0;
        } else {
            value = "''";
        }
        initValue = value;
    }

    ParamDeclaration(Object type, Object identifier, Object obj) {
        this(type, identifier);
        next = (ParamDeclaration) obj;
    }

    public void reset() {
        value = initValue;
    }

    public ParamDeclaration getNext() {
        return next;
    }


    @Override
    public Type getType() {
        return type;
    }

    @Override
    public String getIdentifier() {
        return identifier;
    }

    @Override
    public Object getValue() {
        return value;
    }

    @Override
    public void setValue(Object obj) {
        this.value = obj;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        String out = type.getDescription() + " " + identifier;
        return out;
    }

    /**
     * This method accepts a visitor. The visitor will then have access to this instance
     * for code validation and execution.
     * @param visitor the visitor to accept.
     */
    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }
}
