package parser.parsetree;

import java.util.ArrayList;
import java.util.List;

/**
 * This is a wrapper class for unary conditional expressions.
 * Its instances will hold an assignment operator and an operand.
 */
public class UnaryCondition extends ConditionalExpression {

    private UnOp op;
    private Object operand;

    public UnaryCondition(Object op, Object o) {
        this.op = UnOp.getName(op.toString());
        this.operand = o;
    }

    public Object getOperand() {
        return operand;
    }

    public UnOp getOperator() {
        return op;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        return "(" + op.asString() + operand.toString() + ")";
    }

}
