package parser.parsetree;

import parser.parsetree.interfaces.Declaration;
import parser.parsetree.interfaces.Visitor;

/**
 * This is a wrapper class for variable declarations.
 * It holds the data type of the variable, the identifier and a value.
 * During initialization, the initialized value will be stored, which will allow to run parts of the code -
 * or the whole code - multiple times.
 */
public class VariableDeclaration extends Statement implements Declaration {

    private Type type;
    private String identifier;
    private Object value;
    private Object initValue;

    /**
     * This constructor will create a wrapper for a variable declaration without initial value.
     * The value of the declared variable will be initialized to the default value of the according data type.
     * @param type the data type.
     * @param identifier the identifier.
     */
    public VariableDeclaration(Object type, String identifier) {
        this.type = Type.getByName(type);
        this.identifier = identifier;
        this.value = Type.getByName(type).getDefaultValue();
        this.initValue = value;
    }

    /**
     * This constructor will create a wrapper for a variable declaration.
     * @param type the data type.
     * @param identifier the identifier.
     * @param value the value to be assigned initially.
     */
    public VariableDeclaration(Object type, String identifier, Object value) {
        this(type, identifier);
        this.value = value;
        this.initValue = value;
    }

    /**
     * Returns the data type of this variable declaration.
     * @return the data type.
     */
    @Override
    public Type getType() {
        return type;
    }

    /**
     * Returns the identifier of this variable declaration.
     * @return the identifier.
     */
    @Override
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Returns the value of this variable.
     * @return the value.
     */
    @Override
    public Object getValue() {
        return value;
    }

    /**
     * Allows to set a new value to this variable.
     * @param obj the value to set.
     */
    @Override
    public void setValue(Object obj) {
        this.value = obj;
    }

    /**
     * Resets the value of this variable to the initially initialized default value.
     */
    public void reset() {
        value = initValue;
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        String out =  type.getIdentifier() + " " + identifier + " = " + value;
        if (value instanceof FunctionCallStatement) {
            out = out.substring(0, out.length()-2);
        }
        return  out + ";\n";
    }

    /**
     * This method accepts a visitor. The visitor will then have access to this instance
     * for code validation and execution.
     * @param visitor the visitor to accept.
     */
    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }
}
