package parser.parsetree.instructions;

import parser.parsetree.Keyword;
import parser.parsetree.interfaces.ConditionalExpression;

/**
 * This is a wrapper class for binary conditional expressions.
 * Its instances will hold an assignment operator and two operands.
 */
public class BinaryCondition extends BinaryExpr implements ConditionalExpression {

    /**
     * This constructor will instantiate a wrapper for a binary conditional expression.
     *
     * @param operator the operator.
     * @param operand1 the first operand.
     * @param operand2 the second operand.
     * @param left     the start index.
     * @param right    the end index.
     */
    public BinaryCondition(Object operator, Object operand1, Object operand2, int left, int right) {
        super(operator, operand1, operand2, left, right);
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     *
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        return "(" + getOperand1().toString() + " " + getOperator().getLiteral() + " " + getOperand2().toString() + ")";
    }

    /**
     * This method returns the binary condition as representation of the parse tree.
     *
     * @return a snipped of the parse tree.
     */
    @Override
    public String getParseTree() {
        StringBuilder out = getStringBuilder(this);
        appendKeyword(out, Keyword.BL, 1);
        evaluateExpression(out, getOperand1(), 1);
        appendLine(out, "ConditionalOperator", 1);
        appendBinOp(out, getOperator(), 2);
        evaluateExpression(out, getOperand2(), 1);
        appendKeyword(out, Keyword.BR, 1);
        return out.toString();
    }

}
