package parser.parsetree.instructions;

import parser.parsetree.UnaryOperator;

/**
 * This is a wrapper class for unary expressions.
 * Its instances will hold an assignment operator and an operand.
 */
public class UnaryExpression extends UnaryExpr {

    /**
     * This constructor will instantiate a wrapper for a binary expression.
     *
     * @param operator the operator.
     * @param operand  the operand.
     * @param left     the start index.
     * @param right    the end index.
     */
    public UnaryExpression(Object operator, Object operand, int left, int right) {
        super(operator, operand, left, right);
    }

    /**
     * The toString method provides a pretty-printable String
     * of this parse tree component.
     * It is generated by the contents of this instance and may not be equal to the original code.
     *
     * @return the pretty-printed code.
     */
    @Override
    public String toString() {
        String out = getOperand().toString();
        UnaryOperator op = getOperator();
        if (op == UnaryOperator.DEC || op == UnaryOperator.INC) {
            out += op.getLiteral();
        } else {
            out = op.getLiteral() + out;
        }
        return out;
    }

    /**
     * This method returns the unary expression as representation of the parse tree.
     *
     * @return a snipped of the parse tree.
     */
    @Override
    public String getParseTree() {
        StringBuilder out = getStringBuilder(this);
        UnaryOperator op = getOperator();
        if (op != UnaryOperator.DEC && op != UnaryOperator.INC) {
            appendUnOp(out, op, 1);
        }
        appendNestedComponents(out, getOperand(), 1);
        if (op == UnaryOperator.DEC || op == UnaryOperator.INC) {
            appendUnOp(out, op, 1);
        }
        return out.toString();
    }

}